# TODO: NEED TO FIX CONFIG.yml after /randomizer shuffle
# Randomizer @version@ by querlenker (a fork of motz0815´s plugin)
#
#
# Adjusting this value here will not change anything until you reload or restart the server itself.



# The Plugin is activated by default, if you want to deactivate it, use the ingame command "/randomizer stop"

activated: true

# The blacklist is a list of items, that the plugin won't use as randomized items for BLOCKS!

blacklist:
  - MATERIAL.AIR
  - MATERIAL.WATER
  - MATERIAL.LAVA
  - MATERIAL.FIRE
  - MATERIAL.BEDROCK
  - MATERIAL.JIGSAW
  - MATERIAL.COMMAND_BLOCK
  - MATERIAL.STRUCTURE_BLOCK
  - MATERIAL.BARRIER



