name: Randomizer
main: xyz.motz.randomizer.main.Randomizer
author: querlenker
version: @version@
api-version: @apiVersion@
folia-supported: true

description: "The ultimate Randomizer for your Minecraft Server!"

commands:
  randomizer:
    description: "Prints a little help message."
    usage: "/randomizer"